{{- if .Values.secrets.enabled }}

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "attestor.fullname" . }}-secrets
spec:
  provider: aws
  parameters:
    region: {{ .Values.secrets.aws.region }}
    objects: |
      - objectName: "{{ .Values.secrets.aws.secretName }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: keys_yaml
            objectAlias: keys.yaml
          - path: config_yaml
            objectAlias: config.yaml
          - path: mtls.ca_certificate
            objectAlias: ca.crt
          - path: mtls.attestor_certificate
            objectAlias: {{ .Values.chainService.name }}.crt
          - path: mtls.attestor_key
            objectAlias: {{ .Values.chainService.name }}.key

{{- end }}