{{- if not .Values.isCICD }}

{{- /* Check if the pre-existing secret exists */ -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace .Values.secret_name -}}

{{- if not $existing }}
# Secret does not exist — creating a placeholder
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret_name }}
type: Opaque
stringData:
  keys.yaml: |
    # Placeholder secret for local/test installs
    chain: {}
{{- else }}
# Skipping creation — pre-existing Secret "{{ .Values.secret_name }}" detected
{{- end }}

{{- else }}
# CI/CD environment — create ConfigMap instead
apiVersion: v1
kind: ConfigMap
metadata:
  name: attestor-keys
data:
  keys.yaml: |
    chain:
      ethereum: {}
      aleo: {}
{{- end }}
