apiVersion: v1
kind: Service
metadata:
  name: signingservice
spec:
  type: {{ .Values.service.type }}
  selector:
    app: signingservice
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
