name: e2eAttestor
chains:
    - name: aleo
      chain_id: "6694886634403"
      chain_type: aleo
      bridge_contract: token_bridge_stg_v2.aleo
      node_url: https://api.explorer.aleo.org/v1|testnet
      pkt_validity_wait_dur: 1m0s
      feed_pkt_wait_dur: 0s
      finality_height: 21
      wallet_path: ""
      dest_chains:
        - ethereum
        - base
      wallet_address: aleo1jelsappz5y0cy54cdqukc6xyvz45f35t99mgmlmu3uu7pndvayyqmnx5za
      sequence_num_start:
        ethereum: 1
      start_height: 0
      filter_topic: ""
      retry_packet_wait_dur: 2m0s
      prune_base_seq_num_wait_dur: 5m0s
      average_block_gen_dur: 3s
    - name: ethereum
      chain_id: "28556963657430695"
      chain_type: ethereum
      bridge_contract: 0x302f22Ce7bAb6bf5aEFe6FFBa285E844c7F38EA6
      node_url: https://eth-sepolia.g.alchemy.com/v2/WddzdzI2o9S3COdT73d5w6AIogbKq4X-
      pkt_validity_wait_dur: 2m0s
      feed_pkt_wait_dur: 1m0s
      finality_height: 1
      wallet_path: ""
      dest_chains:
        - aleo
      wallet_address: 0x832894550007B560BD35d28Ce564c2CCD690318F
      sequence_num_start: {}
      start_height: 6243094
      filter_topic: 0x23b9e965d90a00cd3ad31e46b58592d41203f5789805c086b955e34ecd462eb9
      retry_packet_wait_dur: 1m0s
      prune_base_seq_num_wait_dur: 1m0s
      average_block_gen_dur: 12s
    - name: base
      chain_id: "84532"
      chain_type: ethereum
      bridge_contract: ""
      node_url: wss://base-sepolia.drpc.org
      pkt_validity_wait_dur: 2m0s
      feed_pkt_wait_dur: 1m0s
      finality_height: 1
      wallet_path: ""
      dest_chains:
        - aleo
      wallet_address: 0x832894550007B560BD35d28Ce564c2CCD690318F
      sequence_num_start: {}
      start_height: 22689851
      filter_topic: 0x23b9e965d90a00cd3ad31e46b58592d41203f5789805c086b955e34ecd462eb9
      retry_packet_wait_dur: 1m0s
      prune_base_seq_num_wait_dur: 1m0s
      average_block_gen_dur: 2s
log:
    encoding: console
    output_dir: log
db_dir: ""
consume_packet_workers: 10
mode: dev
signing_service:
    host: signingservice
    port: 8080
    endpoint: /sign
    scheme: http
    username: username
    password: password
collector_service:
    uri: https://staging-aleomtls.venture233.xyz
    collector_wait_dur: 1h0m0s
    ca_certificate: /home/aanya/ibriz/aleo/bridge/verulink/attestor/chainService/.mtls/ca.cer
    attestor_certificate: /home/aanya/ibriz/aleo/bridge/verulink/attestor/chainService/.mtls/attestor9.crt
    attestor_key: /home/aanya/ibriz/aleo/bridge/verulink/attestor/chainService/.mtls/attestor9.key
check_health_service: 1m0s
metrics:
    host: 172.17.0.1:9091
    job_name: e2etest-push-gateway
