import { BridgeContract } from "../artifacts/js/bridge";
import { CouncilContract } from "../artifacts/js/council";
import { Token_serviceContract } from "../artifacts/js/token_service";
import { Wrapped_tokenContract } from "../artifacts/js/wrapped_token";
import { evm2AleoArr, string2AleoArr } from "../test/utils";

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

const setup = async () => {
  const bridge = new BridgeContract({
    networkName: "testnet3",
    privateKey: "APrivateKey1zkp8CZNn3yeCseEtxuVPbDCwSyhGW6yZKUYKfgXmcpoGPWH",
    mode: "execute"
  });
  const tokenService = new Token_serviceContract({
    networkName: "testnet3",
    privateKey: "APrivateKey1zkp8CZNn3yeCseEtxuVPbDCwSyhGW6yZKUYKfgXmcpoGPWH",
    mode: "execute"
  });
  const wrappedToken = new Wrapped_tokenContract({
    networkName: "testnet3",
    privateKey: "APrivateKey1zkp8CZNn3yeCseEtxuVPbDCwSyhGW6yZKUYKfgXmcpoGPWH",
    mode: "execute"
  });
  const council = new CouncilContract({
    networkName: "testnet3",
    privateKey: "APrivateKey1zkp8CZNn3yeCseEtxuVPbDCwSyhGW6yZKUYKfgXmcpoGPWH",
    mode: "execute",
  });

  let tx;

  // USDC Contract Address on Ethereum
  const USDC = "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48";

  // User Address on Ethereum
  const ethUser = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266";

  // Token Service Contract Address on Ethereum
  const ethTsContract = "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48";

  // Token Service Contract on Aleo
  const aleoTsContract =
    "aleo1r55t75nceunfds6chwmmhhw3zx5c6wvf62jed0ldyygqctckaurqr8fnd3";

  // Wrapped USDC Contract 
  const wUSDC =
    "aleo1zzy2c66uf46wvtxd0uck965mzj2cn7fn7dl9tgftw7tedl9f3cgsqhsgdz";

  // User address on Aleo
  const aleoUser =
    "aleo1rhgdu77hgyqd3xjj8ucu3jj9r2krwz6mnzyd80gncr5fxcwlh5rsvzp9px";


  // Deploy contracts
  // await bridge.deploy();
  // await wrappedToken.deploy();
  await tokenService.deploy();
  tx = await council.deploy();
  await tx.wait();

  // Initialize council program with a single council member and 1/5 threshold
  const councilMember =
    "aleo1rhgdu77hgyqd3xjj8ucu3jj9r2krwz6mnzyd80gncr5fxcwlh5rsvzp9px";
  const councilThreshold = 1;
  await council.initialize(
    councilMember,
    councilMember,
    councilMember,
    councilMember,
    councilMember,
    councilThreshold
  );

  const councilAddress = "aleo17kz55dul4jmqmw7j3c83yh3wh82hlxnz7v2y5ccqzzj7r6yyeupq4447kp";
  // Initialize bridge
  const attestor = "aleo1rhgdu77hgyqd3xjj8ucu3jj9r2krwz6mnzyd80gncr5fxcwlh5rsvzp9px"
  await bridge.bridge_initialize(
    1,
    attestor,
    attestor,
    attestor,
    attestor,
    attestor,
    councilAddress
  );
  await wrappedToken.wrapped_token_initialize(councilAddress);
  await tokenService.token_service_initialize(councilAddress);

  const ethChainId = 1
  await council.prop_add_new_token(
    1,
    string2AleoArr("Wrapped USDC", 32), // name
    string2AleoArr("USDC", 16), // symbol
    18, // decimal
    ethChainId,
    evm2AleoArr(USDC) // USDC address on Eth
  );
  await council.exec_add_new_token(
    1,
    string2AleoArr("Wrapped USDC", 32), // name
    string2AleoArr("USDC", 16), // symbol
    18, // decimal
    ethChainId,
    evm2AleoArr(USDC) // USDC address on Eth
  );

  // The address is generated by taking the hash of TokenInfo
  // TODO: create a function to get the address from the name
  // aleoProgramToAddress(program.aleo)
  // 
  const minimumTransfer = BigInt(100)

  await council.prop_enable_new_token(1, wUSDC, minimumTransfer, 10_00, 1); // 10% in one block
  await council.exec_enable_new_token(1, wUSDC, minimumTransfer, 10_00, 1);

  // TODO: token_service.address()
  await council.prop_enable_service(1, "aleo1r55t75nceunfds6chwmmhhw3zx5c6wvf62jed0ldyygqctckaurqr8fnd3");
  await council.exec_enable_service(1, "aleo1r55t75nceunfds6chwmmhhw3zx5c6wvf62jed0ldyygqctckaurqr8fnd3");

  // Approve Ethereum Chain
  await council.prop_approve_chain_bridge(1, ethChainId);
  await council.exec_approve_chain_bridge(1, ethChainId);

  const tsEthereum = "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
  await council.prop_support_chain_ts(1, ethChainId, evm2AleoArr(tsEthereum));
  tx = await council.exec_support_chain_ts(1, ethChainId, evm2AleoArr(tsEthereum));
  tx.wait()

};

setup();
