name: Test and Coverage

on:
  push:
    tags:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      # Install and setup Go
      - name: Set up Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
          cache: true  # Enable automatic Go module caching

      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup cache for Go modules
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: go-mod-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-mod-${{ runner.os }}-

      # Run unit tests with coverage
      - name: Run unit tests
        run: make test
        continue-on-error: true

      # Verify coverage file exists before upload
      - name: Check if coverage file exists
        run: |
          if [ ! -f ./coverage.out ]; then
            echo "Coverage file not found! Skipping upload."
            exit 1
          fi

      # Upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
          fail_ci_if_error: true  # Ensures CI fails if upload fails
