name: Create and publish a Docker image

on:
  push:
    tags:
    - '**'
    branches:
    - 'main'
    - '**'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: attestor 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: test
        run: pwd & ls
      - name: Build and push Docker image - chainService
        uses: docker/build-push-action@v3
        with:
          context: ./chainService
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/chainservice
          tag: latest

      - name: Build and push Docker image - signingService
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./signingService/Dockerfile
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/signingservice
          tag: latest

      