name: Create and publish a Docker image

on:
  push:
    tags:
    - '**'
    branches:
    - 'main'
    - '**'
    
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image - signingService
        uses: docker/build-push-action@v3
        with:
          context: ./attestor/signingService
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/signingservice
          tag: latest

      - name: Build and push Docker image - chainService
        uses: docker/build-push-action@v3
        with:
          context: ./attestor/chainService
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/chainservice
          tag: latest