name: Solidity contracts Codecov

env:
  FOUNDRY_PROFILE: ci

on:
  pull_request:
    branches:
      - "**"


defaults:
  run:
    working-directory: solidity

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Coverage
        run: npx hardhat coverage

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          flags: unittests
          name: codecov-coverage
